### ISSUE TITLE
error when install

### ISSUE THREAD

**Issue by diorz38** [Hardeepcoder/larashop55#1]
i try this but get error like this:

In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'larashop55.products' doesn't exist (SQL: select * from `
  products`)

every artisan command ended with that error.
i've connect to mydatabase.
what do i wrong.

**Comment by Hardeepcoder** [comment]
create products table in your database, make sure db config successfully ?
