### ISSUE TITLE
ReflectionException (-1) Class admin does not exist

### ISSUE THREAD

**Issue by marDev23** [Hardeepcoder/larashop55#2]
when opening route admin

**Comment by Hardeepcoder** [comment]
You need to create admin middleware

**Comment by marDev23** [comment]
sorry to ask but what should i put?

**Comment by Hardeepcoder** [comment]
I have video tutorial title like multi auth, I explained everything. 
 
  On Sun, Feb 4, 2018 at 5:35 PM, marDev23<notifications@github.com> wrote:   
sorry to ask but what should i put?
